name: Tests

on:
  push:
    branches: ['main', 'develop']
  pull_request:
    branches: ['main', 'develop']

jobs:
  api-tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2]

    name: API Tests | PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: ctype, curl, dom, fileinfo, filter, hash, json, libxml, mbstring, openssl, pcre, phar, session, tokenizer, xml, xmlwriter
          ini-values: error_reporting=E_ALL
          tools: composer:v2
          coverage: xdebug

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --no-suggest --prefer-dist
        working-directory: ./api

      - name: Execute tests
        run: composer test-coverage
        working-directory: ./api

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        if: matrix.php == '8.2'
        with:
          files: coverage.xml
